[workspace]
channels = ["conda-forge", "bioconda", "bioconda", "conda-forge"]
name = "bioinfor-sw-TFinder"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"

[pypi-dependencies]
biopython = ">=1.86, <2"
altair = "~=5.5.0"
deprecation = "~=2.1.0"
future = ">=1.0.0, <2"
hydralit-components = ">=1.0.10, <2"
logomaker = "~=0.8"
numpy = "~=1.26.4"
openpyxl = ">=3.1.5, <4"
pandas = "~=2.2.2"
plotly = ">=6.5.0, <7"
requests = "~=2.32.3"
stqdm = "~=0.0.5"
streamlit = "~=1.40.1"
streamlit-analytics = ">=0.4.1, <0.5"
streamlit-lottie = ">=0.0.5, <0.0.6"
tqdm = "~=4.66.4"
bs4 = "~=0.0.2"
beautifulsoup4 = "~=4.12.3"
pillow = "~=10.3.0"
scipy = ">=1.16.3, <2"
matplotlib = ">=3.10.8, <4"
scikit-learn = ">=1.8.0, <2"
